use_frameworks!

target 'SolaHomeModule_Example' do
  pod 'SolaHomeModule', :path => '../'

  target 'SolaHomeModule_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
